import { useNavigate } from 'react-router-dom'

const PIPELINE = [
  { step:'01', label:'Lexer',       sub:'PLY lex rules',      icon:'◈', color:'#22d3ee',
    desc:'Tokenizes source using t_ rule functions with regex patterns. 35+ token types including keywords, literals, operators.' },
  { step:'02', label:'Parser',      sub:'PLY yacc SLR(1)',     icon:'⬢', color:'#a78bfa',
    desc:'SLR(1) grammar with p_ rule functions. Builds full AST with operator precedence encoded in grammar levels.' },
  { step:'03', label:'Semantic',    sub:'Symbol table',        icon:'◎', color:'#fb923c',
    desc:'Multi-scope symbol tables, type checking, undeclared variable detection, unused variable warnings.' },
  { step:'04', label:'LLVM IR',     sub:'GCC GIMPLE / text',   icon:'◎', color:'#4ade80',
    desc:'Generates LLVM IR via GCC\'s internal dump or structured text IR with proper SSA form hints.' },
  { step:'05', label:'Assembly',    sub:'GCC x86-64',          icon:'⚙', color:'#f472b6',
    desc:'Real x86-64 AT&T/Intel syntax assembly generated by GCC -S with optimization flag control.' },
  { step:'06', label:'Machine Code',sub:'objdump disasm',      icon:'▣', color:'#fbbf24',
    desc:'Hex bytes + Intel disassembly from objdump. Per-function breakdown with offset, bytes, and mnemonic.' },
  { step:'07', label:'Execute',     sub:'Native binary',       icon:'▶', color:'#4ade80',
    desc:'Compiles and runs the actual binary. Captures stdout/stderr with configurable stdin input support.' },
]

export default function Home() {
  const nav = useNavigate()
  return (
    <div style={{ height:'100%', overflowY:'auto', padding:'36px 44px 40px' }}>
      <div style={{ maxWidth:880 }}>
        {/* Badge */}
        <div style={{ display:'inline-flex', alignItems:'center', gap:8,
          background:'rgba(74,222,128,0.07)', border:'1px solid rgba(74,222,128,0.18)',
          borderRadius:20, padding:'5px 14px', marginBottom:22,
          fontSize:11, color:'var(--accent)', fontWeight:700, letterSpacing:'0.8px',
          fontFamily:'var(--font-mono)',
        }}>
          <div style={{ width:6, height:6, borderRadius:'50%', background:'var(--accent)',
            boxShadow:'0 0 8px var(--accent)', animation:'glow 2s ease-in-out infinite' }} />
          PLY LEX + YACC · GCC TOOLCHAIN · REAL MACHINE CODE
        </div>

        {/* Hero */}
        <h1 style={{ fontSize:44, fontWeight:800, lineHeight:1.08, letterSpacing:'-1.5px',
          marginBottom:16 }}>
          <span style={{ background:'linear-gradient(135deg,#e2e8f0,#94a3b8)',
            WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent' }}>
            MiniC Compiler
          </span>
          <br />
          <span style={{ background:'linear-gradient(90deg,#4ade80,#22d3ee)',
            WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent' }}>
            using LLVM
          </span>
        </h1>

        <p style={{ fontSize:15, color:'var(--text2)', lineHeight:1.75,
          maxWidth:560, marginBottom:28 }}>
          A full-stack compiler built on <strong style={{ color:'var(--text)' }}>PLY lex+yacc</strong> —
          transforms C source through 7 stages from tokenization
          to <strong style={{ color:'var(--text)' }}>real x86-64 machine code</strong>,
          with AST visualization, LLVM IR, and live execution.
        </p>

        {/* CTAs */}
        <div style={{ display:'flex', gap:10, marginBottom:44 }}>
          {[
            { label:'Open Compiler →', to:'/compiler', primary:true },
            { label:'View AST', to:'/ast', primary:false },
            { label:'History', to:'/history', primary:false },
          ].map(btn => (
            <button key={btn.to} onClick={() => nav(btn.to)} style={{
              padding:'10px 22px', borderRadius:8, fontSize:13, fontWeight:btn.primary?700:500,
              background: btn.primary ? 'var(--accent)' : 'transparent',
              color: btn.primary ? '#0a0c10' : 'var(--text2)',
              border: btn.primary ? 'none' : '1px solid var(--border2)',
              fontFamily:'var(--font-ui)', transition:'all 0.15s',
              boxShadow: btn.primary ? '0 0 20px rgba(74,222,128,0.25)' : 'none',
            }}
              onMouseEnter={e => { e.currentTarget.style.opacity='0.85'; e.currentTarget.style.transform='translateY(-1px)' }}
              onMouseLeave={e => { e.currentTarget.style.opacity='1'; e.currentTarget.style.transform='none' }}
            >{btn.label}</button>
          ))}
        </div>

        {/* Pipeline */}
        <div style={{ marginBottom:36 }}>
          <div style={{ fontSize:11, fontWeight:700, textTransform:'uppercase',
            letterSpacing:'1.5px', color:'var(--text3)', marginBottom:14 }}>
            7-Stage Compiler Pipeline
          </div>
          <div style={{ display:'grid', gap:8 }}>
            {PIPELINE.map((p,i) => (
              <div key={i} style={{
                display:'flex', gap:14, alignItems:'flex-start',
                background:'var(--bg2)', borderRadius:10,
                border:'1px solid var(--border)', padding:'14px 18px',
                transition:'border-color 0.2s, transform 0.2s',
              }}
                onMouseEnter={e => { e.currentTarget.style.borderColor=p.color+'44'; e.currentTarget.style.transform='translateX(2px)' }}
                onMouseLeave={e => { e.currentTarget.style.borderColor='var(--border)'; e.currentTarget.style.transform='none' }}
              >
                <div style={{ flexShrink:0, display:'flex', alignItems:'center', gap:10 }}>
                  <span style={{ fontSize:10, color:'var(--text3)', fontFamily:'var(--font-mono)',
                    width:22 }}>{p.step}</span>
                  <div style={{ width:32, height:32, borderRadius:8,
                    background:`${p.color}18`, border:`1px solid ${p.color}33`,
                    display:'flex', alignItems:'center', justifyContent:'center',
                    fontSize:16, color:p.color }}>
                    {p.icon}
                  </div>
                </div>
                <div style={{ flex:1 }}>
                  <div style={{ display:'flex', alignItems:'center', gap:8, marginBottom:3 }}>
                    <span style={{ fontWeight:700, fontSize:13, color:'var(--text)' }}>{p.label}</span>
                    <span style={{ fontSize:10, fontFamily:'var(--font-mono)',
                      background:`${p.color}15`, color:p.color,
                      borderRadius:4, padding:'1px 7px' }}>{p.sub}</span>
                  </div>
                  <p style={{ fontSize:12, color:'var(--text2)', lineHeight:1.6, margin:0 }}>{p.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Language features */}
        <div style={{ background:'var(--bg2)', borderRadius:12,
          border:'1px solid var(--border)', padding:'18px 22px' }}>
          <div style={{ fontSize:11, fontWeight:700, textTransform:'uppercase',
            letterSpacing:'1.5px', color:'var(--text3)', marginBottom:12 }}>
            Language Support
          </div>
          <div style={{ display:'flex', flexWrap:'wrap', gap:6 }}>
            {[
              'int / float / char / void',
              'Arithmetic + − × ÷ %',
              'Bitwise & | ^ ~ << >>',
              'if / else if / else',
              'while / for / do-while',
              'break / continue',
              'return',
              'printf / scanf',
              'Recursive functions',
              'Multi-param functions',
              'Nested scopes',
              '++ / -- operators',
              '+= -= *= /= shortcuts',
              'Ternary ? :',
              'Comparison == != < > <= >=',
              'Logical && ||',
            ].map(f => (
              <span key={f} style={{ fontSize:11, fontFamily:'var(--font-mono)',
                background:'rgba(74,222,128,0.06)', color:'var(--accent)',
                border:'1px solid rgba(74,222,128,0.12)', borderRadius:5,
                padding:'3px 9px' }}>✓ {f}</span>
            ))}
          </div>
        </div>
      </div>
      <style>{`@keyframes glow { 0%,100%{opacity:1} 50%{opacity:0.4} }`}</style>
    </div>
  )
}
